import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Logo from './img/logo.png';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wallet Finder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="header"></div>
        {children}
        </body>
    </html>
  );
}
